version: '3.5'

services:
  proxy:
    image: itzg/bungeecord:latest
    container_name: mcproxy
    environment:
      DEBUG: ${DEBUG_MODE}
      TYPE: VELOCITY
    ports:
      - "25565:25577"
    restart: unless-stopped
    volumes:
      - ./proxy:/server
      - ./extras/velocity:/extras
    networks:
      carsonet:
        ipv4_address: 172.20.0.2

  mclobby:
    image: itzg/minecraft-server:latest
    container_name: mclobby
    environment:
      DEBUG: ${DEBUG_MODE}
      EULA: "TRUE"
      MEMORY: 2G
      VERSION: "1.18.2"
      TYPE: "PUFFERFISH"
      ONLINE_MODE: "FALSE"
      GAMEMODE: ADVENTURE
      MAX_PLAYERS: 150
      MOTD: "§cCMCThrowback SMPOnline Lobby"
      ALLOW_RCON: "FALSE"
      ALLOW_NETHER: "FALSE"
      SPAWN_NPCS: "FALSE"
      SPAWN_ANIMALS: "FALSE"
      SPAWN_MONSTERS: "FALSE"
      SPIGET_RESOURCES: "69545" # Real Time Plugin 
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./mc/lobby:/data
      - ./extras/lobby:/extras
#    depends_on:
#      proxy:
#        condition: "service_healthy"
    networks:
      carsonet:
        ipv4_address: 172.20.0.3

  mc-s1:
    container_name: mc-s1
    image: itzg/minecraft-server:latest
    environment:
      DEBUG: ${DEBUG_MODE}
      EULA: "TRUE"
      MEMORY: 4G
      VERSION: "1.17.1"
      TYPE: "PUFFERFISH"
      ONLINE_MODE: "FALSE"
      MAX_PLAYERS: 75
      MOTD: "§cCMCThrowback SMPOnline §oSeason 1 Server"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./mc/smp/s1:/data
      - ./extras/s1:/extras
#    depends_on:
#      proxy:
#        condition: "service_healthy"
    networks:
      carsonet:
        ipv4_address: 172.20.0.4

  mc-s2:
    container_name: mc-s2
    image: itzg/minecraft-server:latest
    environment:
      DEBUG: ${DEBUG_MODE}
      EULA: "TRUE"
      MEMORY: 4G
      VERSION: "1.18.2"
      TYPE: "PUFFERFISH"
      ONLINE_MODE: "FALSE"
      MAX_PLAYERS: 75
      MOTD: "§bCMCThrowback SMPOnline §oSeason 2 Server"
      ALLOW_RCON: "FALSE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./mc/smp/s2:/data
      - ./etras/s2:/extras
#    depends_on:
#      proxy:
#        condition: "service_healthy"
    networks:
      carsonet:
        ipv4_address: 172.20.0.5

networks:
  carsonet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
