version: '3.5'

services:
  proxy:
    image: itzg/bungeecord:latest
    container_name: mcproxy
    environment:
      DEBUG: ${DEBUG_MODE}
      TYPE: VELOCITY
      ALLOW_RCON: ${ALLOW_RCON}
    ports:
      - "25565:25577"
    restart: unless-stopped
    volumes:
      - ./proxy:/server
      - ./extras:/extras
      - ./plugins/velocity:/plugins
    networks:
      carsonet:
        ipv4_address: 172.20.0.2

  mclobby:
    image: itzg/minecraft-server:latest
    container_name: mclobby
    environment:
      DEBUG: ${DEBUG_MODE}
      EULA: "TRUE"
      MEMORY: 2G
      VERSION: "1.18.2"
      TYPE: "PUFFERFISH"
      ONLINE_MODE: "FALSE"
      GAMEMODE: ADVENTURE
      MAX_PLAYERS: 150
      MOTD: "§cCMCThrowback SMPOnline Lobby"
      ALLOW_RCON: ${ALLOW_RCON}
      ALLOW_NETHER: "FALSE"
      SPAWN_NPCS: "FALSE"
      SPAWN_ANIMALS: "FALSE"
      SPAWN_MONSTERS: "FALSE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ${LOBBY_DIR}:/data
      - ./extras:/extras
      - ./plugins/smp:/plugins
#    depends_on:
#      proxy:
#        condition: "service_healthy"
    networks:
      carsonet:
        ipv4_address: 172.20.0.3

  mc-s1:
    container_name: mc-s1
    image: itzg/minecraft-server:latest
    environment:
      DEBUG: ${DEBUG_MODE}
      EULA: "TRUE"
      MEMORY: 4G
      VERSION: "1.17.1"
      TYPE: "PUFFERFISH"
      ONLINE_MODE: "FALSE"
      MAX_PLAYERS: 75
      MOTD: "§cCMCThrowback SMPOnline §oSeason 1 Server"
      MODS_FILE: "/extras/mods.txt"
      WORLD: "https://archive.org/download/cmcsmplive_s1_s2/SMPOnline/season1.zip"
      ALLOW_RCON: ${ALLOW_RCON}
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ${S1_DIR}:/data
      - ./extras:/extras
      - ./plugins/smp:/plugins
#    depends_on:
#      proxy:
#        condition: "service_healthy"
    networks:
      carsonet:
        ipv4_address: 172.20.0.4

  mc-s2:
    container_name: mc-s2
    image: itzg/minecraft-server:latest
    environment:
      DEBUG: ${DEBUG_MODE}
      EULA: "TRUE"
      MEMORY: 4G
      VERSION: "1.18.2"
      TYPE: "PUFFERFISH"
      ONLINE_MODE: "FALSE"
      MAX_PLAYERS: 75
      MOTD: "§bCMCThrowback SMPOnline §oSeason 2 Server"
      MODS_FILE: "/extras/mods.txt"
      WORLD: "https://archive.org/download/cmcsmplive_s1_s2/SMPOnline/season2.zip"
      ALLOW_RCON: ${ALLOW_RCON}
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ${S2_DIR}:/data
      - ./extras:/extras
      - ./plugins/smp:/plugins
#    depends_on:
#      proxy:
#        condition: "service_healthy"
    networks:
      carsonet:
        ipv4_address: 172.20.0.5

networks:
  carsonet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
