version: '3.5'

services:
  mclobby:
    image: itzg/minecraft-server:latest
    container_name: mclobby
    environment:
      DEBUG: ${DEBUG_MODE}
      EULA: "TRUE"
      MEMORY: 2G
      VERSION: "1.18.2"
      TYPE: "PUFFERFISH"
      ONLINE_MODE: "FALSE"
      GAMEMODE: ADVENTURE
      MAX_PLAYERS: 150
      MOTD: "§cCMCThrowback SMPOnline Lobby"
      MODS_FILE: /extras/mods.txt
      ALLOW_RCON: ${ALLOW_RCON}
      ALLOW_NETHER: "FALSE"
      SPAWN_NPCS: "FALSE"
      SPAWN_ANIMALS: "FALSE"
      SPAWN_MONSTERS: "FALSE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ${LOBBY_DIR}:/data
      - ./plugins/smp:/plugins
      - ${SMP_PLUGINS_FILE}:/extras/mods.txt:ro
    ports:
      - ${LOBBY_PORT}:25565